/**
 * Attendance List Screen - Display attendance entries
 * @format
 */

import React, { useEffect, useMemo, useState } from 'react';
import {
  View,
  Text,
  StyleSheet,
  ScrollView,
  TouchableOpacity,
  StatusBar,
  RefreshControl,
  TextInput,
} from 'react-native';
import { useSafeAreaInsets } from 'react-native-safe-area-context';
import { useNavigation } from '@react-navigation/native';
import { StackNavigationProp } from '@react-navigation/stack';
import { MainStackParamList } from '../../navigation/MainNavigator';
import { getAttendance, type AttendanceEntryApi } from '../../api/attendance';
import { showToast } from '../../utils/toast';
import Ionicons from 'react-native-vector-icons/Ionicons';

type AttendanceListNavigationProp = StackNavigationProp<
  MainStackParamList,
  'AttendanceList'
>;

interface AttendanceEntry {
  id: string;
  date: string;
  dayOfWeek: string;
  type: 'attendance' | 'leave' | 'holiday';
  startTime?: string;
  finishTime?: string;
  breakDuration?: string;
  totalHours?: string;
  notes?: string;
  leaveType?: string;
  holidayName?: string;
}

const toMonthParam = (val: string) => {
  const s = val.trim();
  // accept YYYY-MM only
  if (!/^\d{4}-\d{2}$/.test(s)) return null;
  return s;
};

const stripSeconds = (t?: string | null) => {
  if (!t) return undefined;
  // "09:00:00" -> "09:00"
  const parts = t.split(':');
  if (parts.length >= 2) return `${parts[0].padStart(2, '0')}:${parts[1].padStart(2, '0')}`;
  return t;
};

const decimalHoursToLabel = (val?: string | null) => {
  if (val === null || val === undefined || val === '') return undefined;
  const n = Number(val);
  if (Number.isNaN(n)) return String(val);
  const sign = n < 0 ? '-' : '';
  const abs = Math.abs(n);
  const hours = Math.floor(abs);
  const mins = Math.round((abs - hours) * 60);
  if (hours === 0) return `${sign}${mins}m`;
  if (mins === 0) return `${sign}${hours}h`;
  return `${sign}${hours}h ${mins}m`;
};

const sanitizeNotes = (notes: any) => {
  if (typeof notes !== 'string') return undefined;
  const trimmed = notes.trim();
  if (!trimmed) return undefined;
  // Remove "AUTO-GENERATED" / "auto generated" / "auto_generated" variants.
  const folded = trimmed.toLowerCase().replace(/[^a-z]/g, '');
  if (folded.includes('autogenerated')) return undefined;
  return trimmed;
};

const isZeroDurationLabel = (label?: string) => {
  if (!label) return true;
  const folded = label.toLowerCase().replace(/\s+/g, '');
  return (
    folded === '0m' ||
    folded === '0h' ||
    folded === '0h0m' ||
    folded === '00h:00m' ||
    folded === '00:00' ||
    folded === '0:00'
  );
};

const apiToUiEntry = (e: AttendanceEntryApi): AttendanceEntry => {
  const type: AttendanceEntry['type'] = e.is_leave
    ? 'leave'
    : e.is_public_holiday
      ? 'holiday'
      : 'attendance';

  return {
    id: String(e.id),
    date: e.date,
    dayOfWeek: e.day ?? new Date(e.date).toLocaleDateString('en-US', { weekday: 'short' }),
    type,
    startTime: stripSeconds(e.start_time) ?? undefined,
    finishTime: stripSeconds(e.finish_time) ?? undefined,
    breakDuration: decimalHoursToLabel(e.break_duration),
    totalHours: decimalHoursToLabel(e.total_hours),
    leaveType: e.leave_type ?? undefined,
    holidayName: e.public_holiday_name ?? undefined,
    notes: sanitizeNotes(e.notes),
  };
};

const AttendanceListScreen: React.FC = () => {
  const insets = useSafeAreaInsets();
  const navigation = useNavigation<AttendanceListNavigationProp>();
  const [refreshing, setRefreshing] = useState(false);
  const currentMonth = useMemo(() => {
    const now = new Date();
    const m = String(now.getMonth() + 1).padStart(2, '0');
    return `${now.getFullYear()}-${m}`;
  }, []);
  const [selectedMonth, setSelectedMonth] = useState<string>(() => {
    return currentMonth;
  });
  const [showFilters, setShowFilters] = useState(false);
  const [isLoading, setIsLoading] = useState(false);
  const [entries, setEntries] = useState<AttendanceEntry[]>([]);

  const monthParam = useMemo(() => toMonthParam(selectedMonth), [selectedMonth]);

  const applyMonthFilter = () => {
    if (!monthParam) {
      showToast.error('Month filter', 'Please use format YYYY-MM');
      return;
    }
    loadAttendance();
    setShowFilters(false);
  };

  const resetMonthFilter = () => {
    setSelectedMonth(currentMonth);
    loadAttendance();
    setShowFilters(false);
  };

  const loadAttendance = async (opts?: { silent?: boolean }) => {
    const silent = opts?.silent ?? false;
    if (!silent) setIsLoading(true);
    try {
      const response = await getAttendance({
        month: monthParam ?? undefined,
        per_page: 60,
        page: 1,
      });
      const apiEntries = response.data?.entries ?? [];
      setEntries(apiEntries.map(apiToUiEntry));
      if (!response.success) {
        showToast.error('Attendance', response.message || 'Could not load attendance');
      }
    } catch (err: any) {
      const message =
        err.response?.data?.message ||
        err.message ||
        'Could not load attendance. Please try again.';
      showToast.error('Attendance', message);
    } finally {
      if (!silent) setIsLoading(false);
    }
  };

  const onRefresh = React.useCallback(() => {
    setRefreshing(true);
    loadAttendance({ silent: true }).finally(() => setRefreshing(false));
  }, [monthParam]);

  useEffect(() => {
    loadAttendance();
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [monthParam]);

  const formatDate = (dateString: string) => {
    const date = new Date(dateString);
    return date.toLocaleDateString('en-US', {
      month: 'short',
      day: 'numeric',
      year: 'numeric',
    });
  };

  const renderAttendanceCard = (entry: AttendanceEntry) => {
    if (entry.type === 'leave') {
      return (
        <View key={entry.id} style={styles.card}>
          <View style={styles.cardHeader}>
            <Text style={styles.dateIcon}>📅</Text>
            <View style={styles.dateInfo}>
              <Text style={styles.dateText}>
                {formatDate(entry.date)} ({entry.dayOfWeek})
              </Text>
            </View>
          </View>
          <View style={styles.leaveContainer}>
            <Text style={styles.leaveText}>Leave</Text>
            {entry.leaveType && (
              <Text style={styles.leaveTypeText}>{entry.leaveType}</Text>
            )}
          </View>
        </View>
      );
    }

    if (entry.type === 'holiday') {
      return (
        <View key={entry.id} style={styles.card}>
          <View style={styles.cardHeader}>
            <Text style={styles.dateIcon}>📅</Text>
            <View style={styles.dateInfo}>
              <Text style={styles.dateText}>
                {formatDate(entry.date)} ({entry.dayOfWeek})
              </Text>
            </View>
          </View>
          <View style={styles.holidayContainer}>
            <Text style={styles.holidayText}>Public Holiday</Text>
            {entry.holidayName && (
              <Text style={styles.holidayNameText}>{entry.holidayName}</Text>
            )}
          </View>
        </View>
      );
    }

    const isDayOff =
      !entry.startTime &&
      !entry.finishTime &&
      !entry.totalHours &&
      isZeroDurationLabel(entry.breakDuration);

    return (
      <View key={entry.id} style={styles.card}>
        <View style={styles.cardHeader}>
          <Text style={styles.dateIcon}>📅</Text>
          <View style={styles.dateInfo}>
            <Text style={styles.dateText}>
              {formatDate(entry.date)} ({entry.dayOfWeek})
            </Text>
          </View>
        </View>
        {isDayOff ? (
          <View style={styles.dayOffContainer}>
            <Text style={styles.dayOffText}>Day off</Text>
            <Text style={styles.dayOffSubText}>No working hours recorded</Text>
          </View>
        ) : (
          <View style={styles.timeRow}>
            <Text style={styles.timeRangeText}>
              {entry.startTime && entry.finishTime
                ? `${entry.startTime} - ${entry.finishTime}`
                : entry.startTime || entry.finishTime || '—'}
            </Text>
            <View style={styles.pillsColumn}>
              {!isZeroDurationLabel(entry.breakDuration) && (
                <View style={styles.breakPill}>
                  <Text style={styles.breakPillLabel}>Break</Text>
                  <Text style={styles.breakPillValue}>
                    {entry.breakDuration}
                  </Text>
                </View>
              )}
              <View style={styles.totalHoursPill}>
                <Text style={styles.totalHoursPillLabel}>Total</Text>
                <Text style={styles.totalHoursPillValue}>
                  {entry.totalHours ?? '—'}
                </Text>
              </View>
            </View>
          </View>
        )}
        {entry.notes && (
          <View style={styles.notesContainer}>
            <Text style={styles.notesText}>{entry.notes}</Text>
          </View>
        )}
      </View>
    );
  };

  return (
    <View style={styles.container}>
      <StatusBar barStyle="light-content" backgroundColor="#0d1a5a" />
      
      {/* Notch area - darker colored background */}
      <View style={[styles.notchArea, { height: insets.top }]} />

      {/* Header */}
      <View style={styles.header}>
        <TouchableOpacity
          style={styles.backButton}
          onPress={() => navigation.goBack()}
          activeOpacity={0.7}>
          <View style={styles.backRow}>
            <Ionicons name="arrow-back" size={18} color="#ffffff" />
            <Text style={styles.backButtonText}>Back</Text>
          </View>
        </TouchableOpacity>
        <Text style={styles.headerTitle}>Attendance</Text>
        <TouchableOpacity
          style={styles.filterButton}
          onPress={() => setShowFilters(!showFilters)}
          activeOpacity={0.7}>
          <Ionicons
            name={showFilters ? 'close' : 'options-outline'}
            size={20}
            color="#ffffff"
          />
        </TouchableOpacity>
      </View>

      {/* Filters Section */}
      {showFilters && (
        <View style={styles.filtersContainer}>
          <View style={styles.filtersCard}>
            <View style={styles.filtersHeaderRow}>
              <View style={styles.filtersTitleRow}>
                <Ionicons name="calendar-outline" size={18} color="#1a237e" />
                <Text style={styles.filtersTitle}>Filter by month</Text>
              </View>
              <TouchableOpacity
                style={styles.filtersCloseButton}
                onPress={() => setShowFilters(false)}
                activeOpacity={0.7}>
                <Ionicons name="close" size={18} color="#1a237e" />
              </TouchableOpacity>
            </View>

            <View style={styles.monthInputRow}>
              <Ionicons name="search-outline" size={18} color="#64748b" />
              <TextInput
                style={styles.monthInput}
                placeholder="YYYY-MM"
                placeholderTextColor="#94a3b8"
                value={selectedMonth}
                onChangeText={setSelectedMonth}
                autoCapitalize="none"
                autoCorrect={false}
                keyboardType="numbers-and-punctuation"
                returnKeyType="done"
                maxLength={7}
                onSubmitEditing={applyMonthFilter}
              />
              {!!selectedMonth && (
                <TouchableOpacity
                  style={styles.monthClearButton}
                  onPress={() => setSelectedMonth('')}
                  hitSlop={{ top: 10, bottom: 10, left: 10, right: 10 }}>
                  <Ionicons name="close-circle" size={18} color="#94a3b8" />
                </TouchableOpacity>
              )}
            </View>

            {!monthParam && (
              <Text style={styles.filterHint}>Use format YYYY-MM (example: 2025-11)</Text>
            )}

            <View style={styles.filterActionsRow}>
              <TouchableOpacity
                style={styles.secondaryButton}
                onPress={resetMonthFilter}
                activeOpacity={0.8}>
                <Text style={styles.secondaryButtonText}>This month</Text>
              </TouchableOpacity>
              <TouchableOpacity
                style={styles.primaryButton}
                onPress={applyMonthFilter}
                activeOpacity={0.8}>
                <Text style={styles.primaryButtonText}>Apply</Text>
              </TouchableOpacity>
            </View>
          </View>
        </View>
      )}

      <ScrollView
        style={styles.scrollView}
        contentContainerStyle={styles.scrollContent}
        refreshControl={
          <RefreshControl refreshing={refreshing} onRefresh={onRefresh} />
        }
        showsVerticalScrollIndicator={false}>
        {isLoading && entries.length === 0 ? (
          <View style={styles.emptyContainer}>
            <Text style={styles.emptyText}>Loading attendance…</Text>
          </View>
        ) : entries.length === 0 ? (
          <View style={styles.emptyContainer}>
            <Text style={styles.emptyText}>No attendance records found</Text>
          </View>
        ) : (
          entries.map((entry) => renderAttendanceCard(entry))
        )}
      </ScrollView>
    </View>
  );
};

const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#f5f5f5',
  },
  notchArea: {
    backgroundColor: '#0d1a5a',
    width: '100%',
  },
  header: {
    backgroundColor: '#1a237e',
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: 20,
    paddingBottom: 16,
    paddingTop: 10,
  },
  backRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
  },
  backButton: {
    paddingVertical: 8,
    paddingHorizontal: 4,
  },
  backButtonText: {
    fontSize: 16,
    color: '#ffffff',
    fontWeight: '500',
  },
  headerTitle: {
    fontSize: 20,
    fontWeight: 'bold',
    color: '#ffffff',
  },
  filterButton: {
    paddingVertical: 8,
    paddingHorizontal: 10,
    borderRadius: 10,
    backgroundColor: 'rgba(255,255,255,0.14)',
  },
  filtersContainer: {
    backgroundColor: '#ffffff',
    paddingHorizontal: 16,
    paddingTop: 14,
    paddingBottom: 14,
    borderBottomWidth: 1,
    borderBottomColor: '#e0e0e0',
  },
  filtersCard: {
    backgroundColor: '#f8fafc',
    borderRadius: 14,
    padding: 14,
    borderWidth: 1,
    borderColor: '#e2e8f0',
  },
  filtersHeaderRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginBottom: 12,
  },
  filtersTitleRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
  },
  filtersTitle: {
    fontSize: 14,
    fontWeight: '700',
    color: '#0f172a',
  },
  filtersCloseButton: {
    width: 34,
    height: 34,
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: 10,
    backgroundColor: '#eef2ff',
  },
  monthInputRow: {
    flexDirection: 'row',
    alignItems: 'center',
    borderWidth: 1,
    borderColor: '#e2e8f0',
    backgroundColor: '#ffffff',
    borderRadius: 12,
    paddingHorizontal: 12,
    paddingVertical: 10,
  },
  monthInput: {
    flex: 1,
    marginLeft: 8,
    fontSize: 14,
    color: '#0f172a',
    paddingVertical: 0,
  },
  monthClearButton: {
    marginLeft: 8,
  },
  filterHint: {
    marginTop: 10,
    fontSize: 12,
    color: '#64748b',
  },
  filterActionsRow: {
    flexDirection: 'row',
    gap: 12,
    marginTop: 14,
  },
  secondaryButton: {
    flex: 1,
    backgroundColor: '#ffffff',
    borderWidth: 1,
    borderColor: '#cbd5e1',
    paddingVertical: 12,
    borderRadius: 12,
    alignItems: 'center',
  },
  secondaryButtonText: {
    fontSize: 14,
    fontWeight: '700',
    color: '#1a237e',
  },
  primaryButton: {
    flex: 1,
    backgroundColor: '#1a237e',
    paddingVertical: 12,
    borderRadius: 12,
    alignItems: 'center',
  },
  primaryButtonText: {
    fontSize: 14,
    fontWeight: '700',
    color: '#ffffff',
  },
  scrollView: {
    flex: 1,
  },
  scrollContent: {
    padding: 16,
    paddingBottom: 100,
  },
  card: {
    backgroundColor: '#ffffff',
    borderRadius: 12,
    padding: 16,
    marginBottom: 12,
    shadowColor: '#000',
    shadowOffset: {
      width: 0,
      height: 2,
    },
    shadowOpacity: 0.1,
    shadowRadius: 3.84,
    elevation: 5,
  },
  cardHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 12,
  },
  dateIcon: {
    fontSize: 20,
    marginRight: 12,
  },
  dateInfo: {
    flex: 1,
  },
  dateText: {
    fontSize: 16,
    fontWeight: '600',
    color: '#212121',
  },
  timeInfo: {
    marginBottom: 8,
  },
  timeText: {
    fontSize: 16,
    fontWeight: '500',
    color: '#424242',
  },
  timeRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginTop: 2,
  },
  timeRangeText: {
    fontSize: 15,
    fontWeight: '500',
    color: '#424242',
    flexShrink: 1,
    paddingRight: 12,
  },
  pillsColumn: {
    alignItems: 'flex-end',
    gap: 8,
  },
  breakPill: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#f1f5f9',
    borderRadius: 999,
    paddingVertical: 6,
    paddingHorizontal: 10,
  },
  breakPillLabel: {
    fontSize: 12,
    color: '#475569',
    fontWeight: '600',
    marginRight: 6,
  },
  breakPillValue: {
    fontSize: 12,
    color: '#0f172a',
    fontWeight: '700',
  },
  totalHoursPill: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#eef2ff',
    borderRadius: 999,
    paddingVertical: 6,
    paddingHorizontal: 10,
  },
  totalHoursPillLabel: {
    fontSize: 12,
    color: '#3949ab',
    fontWeight: '600',
    marginRight: 6,
  },
  totalHoursPillValue: {
    fontSize: 12,
    color: '#1a237e',
    fontWeight: '700',
  },
  dayOffContainer: {
    backgroundColor: '#f8fafc',
    borderRadius: 10,
    paddingVertical: 12,
    paddingHorizontal: 14,
    marginTop: 2,
    borderWidth: 1,
    borderColor: '#e2e8f0',
  },
  dayOffText: {
    fontSize: 15,
    fontWeight: '700',
    color: '#0f172a',
  },
  dayOffSubText: {
    marginTop: 4,
    fontSize: 12,
    color: '#64748b',
  },
  detailsRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginBottom: 6,
  },
  detailLabel: {
    fontSize: 14,
    color: '#757575',
  },
  detailValue: {
    fontSize: 14,
    fontWeight: '500',
    color: '#212121',
  },
  notesContainer: {
    marginTop: 8,
    paddingTop: 8,
    borderTopWidth: 1,
    borderTopColor: '#e0e0e0',
  },
  notesText: {
    fontSize: 12,
    color: '#757575',
    fontStyle: 'italic',
  },
  leaveContainer: {
    backgroundColor: '#fff3e0',
    padding: 12,
    borderRadius: 8,
    marginTop: 8,
  },
  leaveText: {
    fontSize: 16,
    fontWeight: '600',
    color: '#e65100',
    marginBottom: 4,
  },
  leaveTypeText: {
    fontSize: 14,
    color: '#e65100',
  },
  holidayContainer: {
    backgroundColor: '#e3f2fd',
    padding: 12,
    borderRadius: 8,
    marginTop: 8,
  },
  holidayText: {
    fontSize: 16,
    fontWeight: '600',
    color: '#1976d2',
    marginBottom: 4,
  },
  holidayNameText: {
    fontSize: 14,
    color: '#1976d2',
  },
  emptyContainer: {
    alignItems: 'center',
    justifyContent: 'center',
    paddingVertical: 60,
  },
  emptyText: {
    fontSize: 16,
    color: '#757575',
  },
});

export default AttendanceListScreen;

