/**
 * Attendance List Screen - Display attendance entries
 * @format
 */

import React, { useEffect, useMemo, useState } from 'react';
import {
  View,
  Text,
  StyleSheet,
  ScrollView,
  TouchableOpacity,
  StatusBar,
  RefreshControl,
  Alert,
  Platform,
} from 'react-native';
import { useSafeAreaInsets } from 'react-native-safe-area-context';
import { useNavigation, useRoute } from '@react-navigation/native';
import { StackNavigationProp } from '@react-navigation/stack';
import { RouteProp } from '@react-navigation/native';
import { MainStackParamList } from '../../navigation/MainNavigator';
import {
  getAttendance,
  getTimesheets,
  getTimesheetDownloadPdfUrl,
  type AttendanceEntryApi,
  type TimesheetListItem,
} from '../../api/attendance';
import { showToast } from '../../utils/toast';
import Ionicons from 'react-native-vector-icons/Ionicons';
import DateTimePicker from '@react-native-community/datetimepicker';
import ReactNativeBlobUtil from 'react-native-blob-util';
import { tokenStorage } from '../../utils/storage';

type AttendanceListNavigationProp = StackNavigationProp<
  MainStackParamList,
  'AttendanceList'
>;
type AttendanceListRouteProp = RouteProp<MainStackParamList, 'AttendanceList'>;

interface AttendanceEntry {
  id: string;
  date: string;
  dayOfWeek: string;
  type: 'attendance' | 'leave' | 'holiday';
  startTime?: string;
  finishTime?: string;
  breakDuration?: string;
  totalHours?: string;
  breakMinutes?: number;
  totalMinutes?: number;
  notes?: string;
  leaveType?: string;
  holidayName?: string;
}

const monthToDate = (month: string): Date => {
  // month: YYYY-MM
  const [y, m] = month.split('-').map(Number);
  if (!y || !m) return new Date();
  return new Date(y, m - 1, 1);
};

const dateToMonth = (d: Date): string => {
  const y = d.getFullYear();
  const m = String(d.getMonth() + 1).padStart(2, '0');
  return `${y}-${m}`;
};

const monthLabel = (month: string): string => {
  const d = monthToDate(month);
  return d.toLocaleDateString('en-US', { month: 'long', year: 'numeric' });
};

const stripSeconds = (t?: string | null) => {
  if (!t) return undefined;
  // "09:00:00" -> "09:00"
  const parts = t.split(':');
  if (parts.length >= 2) return `${parts[0].padStart(2, '0')}:${parts[1].padStart(2, '0')}`;
  return t;
};

const decimalHoursToLabel = (val?: string | null) => {
  if (val === null || val === undefined || val === '') return undefined;
  const n = Number(val);
  if (Number.isNaN(n)) return String(val);
  const sign = n < 0 ? '-' : '';
  const abs = Math.abs(n);
  const hours = Math.floor(abs);
  const mins = Math.round((abs - hours) * 60);
  if (hours === 0) return `${sign}${mins}m`;
  if (mins === 0) return `${sign}${hours}h`;
  return `${sign}${hours}h ${mins}m`;
};

const durationToMinutes = (val?: string | null) => {
  if (val === null || val === undefined || val === '') return undefined;
  if (typeof val === 'number') {
    if (Number.isNaN(val)) return undefined;
    return Math.round(val * 60);
  }
  const raw = String(val).trim();
  if (!raw) return undefined;

  // Decimal hours ("7.50")
  const asNum = Number(raw);
  if (!Number.isNaN(asNum)) return Math.round(asNum * 60);

  // "150h:30m" / "07h:00m" / "7h 30m" / "-1h:15m"
  const hm = raw.match(/^(-?\d+)\s*h(?:\s*[:\s]\s*)?(\d{1,2})?\s*m?$/i);
  if (hm?.[1]) {
    const h = Number(hm[1]);
    const m = hm[2] != null ? Number(hm[2]) : 0;
    if (Number.isNaN(h) || Number.isNaN(m)) return undefined;
    const sign = h < 0 ? -1 : 1;
    return sign * (Math.abs(h) * 60 + Math.abs(m));
  }

  // "45m" / "-30m"
  const mm = raw.match(/^(-?\d+)\s*m$/i);
  if (mm?.[1]) {
    const m = Number(mm[1]);
    if (Number.isNaN(m)) return undefined;
    return m;
  }

  return undefined;
};

const sanitizeNotes = (notes: any) => {
  if (typeof notes !== 'string') return undefined;
  const trimmed = notes.trim();
  if (!trimmed) return undefined;
  // Remove "AUTO-GENERATED" / "auto generated" / "auto_generated" variants.
  const folded = trimmed.toLowerCase().replace(/[^a-z]/g, '');
  if (folded.includes('autogenerated')) return undefined;
  return trimmed;
};

const isZeroDurationLabel = (label?: string) => {
  if (!label) return true;
  const folded = label.toLowerCase().replace(/\s+/g, '');
  return (
    folded === '0m' ||
    folded === '0h' ||
    folded === '0h0m' ||
    folded === '00h:00m' ||
    folded === '00:00' ||
    folded === '0:00'
  );
};

const apiToUiEntry = (e: AttendanceEntryApi): AttendanceEntry => {
  const type: AttendanceEntry['type'] = e.is_leave
    ? 'leave'
    : e.is_public_holiday
      ? 'holiday'
      : 'attendance';

  return {
    id: String(e.id),
    date: e.date,
    dayOfWeek: e.day ?? new Date(e.date).toLocaleDateString('en-US', { weekday: 'short' }),
    type,
    startTime: stripSeconds(e.start_time) ?? undefined,
    finishTime: stripSeconds(e.finish_time) ?? undefined,
    breakDuration: decimalHoursToLabel(e.break_duration),
    totalHours: decimalHoursToLabel(e.total_hours),
    breakMinutes: durationToMinutes(e.break_duration),
    totalMinutes: durationToMinutes(e.total_hours),
    leaveType: e.leave_type ?? undefined,
    holidayName: e.public_holiday_name ?? undefined,
    notes: sanitizeNotes(e.notes),
  };
};

const AttendanceListScreen: React.FC = () => {
  const insets = useSafeAreaInsets();
  const navigation = useNavigation<AttendanceListNavigationProp>();
  const route = useRoute<AttendanceListRouteProp>();
  const [refreshing, setRefreshing] = useState(false);
  const currentMonth = useMemo(() => {
    const now = new Date();
    const m = String(now.getMonth() + 1).padStart(2, '0');
    return `${now.getFullYear()}-${m}`;
  }, []);
  const [appliedMonth, setAppliedMonth] = useState<string>(() => currentMonth);
  const [draftMonth, setDraftMonth] = useState<string>(() => currentMonth);
  const [showFilters, setShowFilters] = useState(false);
  const [showMonthPicker, setShowMonthPicker] = useState(false);
  const [pickerDate, setPickerDate] = useState<Date>(() => monthToDate(currentMonth));
  const [isLoading, setIsLoading] = useState(false);
  const [entries, setEntries] = useState<AttendanceEntry[]>([]);
  const [monthTimesheet, setMonthTimesheet] = useState<TimesheetListItem | null>(null);
  const [downloadingPdf, setDownloadingPdf] = useState(false);

  const monthParam = useMemo(() => appliedMonth, [appliedMonth]);

  useEffect(() => {
    const m = route.params?.month;
    if (m && /^\d{4}-\d{2}$/.test(m) && m !== appliedMonth) {
      setAppliedMonth(m);
      setDraftMonth(m);
      setPickerDate(monthToDate(m));
    }
  }, [appliedMonth, route.params?.month]);

  useEffect(() => {
    if (!showFilters) return;
    setDraftMonth(appliedMonth);
    setPickerDate(monthToDate(appliedMonth));
  }, [showFilters, appliedMonth]);

  const applyMonthFilter = () => {
    setAppliedMonth(draftMonth);
    setShowFilters(false);
  };

  const resetMonthFilter = () => {
    setDraftMonth(currentMonth);
    setAppliedMonth(currentMonth);
    setShowFilters(false);
  };

  const loadAttendance = async (opts?: { silent?: boolean }) => {
    const silent = opts?.silent ?? false;
    if (!silent) setIsLoading(true);
    try {
      const response = await getAttendance({
        month: monthParam ?? undefined,
        per_page: 60,
        page: 1,
      });
      const apiEntries = response.data?.entries ?? [];
      setEntries(apiEntries.map(apiToUiEntry));
      if (!response.success) {
        showToast.error('Attendance', response.message || 'Could not load attendance');
      }
    } catch (err: any) {
      const message =
        err.response?.data?.message ||
        err.message ||
        'Could not load attendance. Please try again.';
      showToast.error('Attendance', message);
    } finally {
      if (!silent) setIsLoading(false);
    }
  };

  const onRefresh = React.useCallback(() => {
    setRefreshing(true);
    loadAttendance({ silent: true }).finally(() => setRefreshing(false));
  }, [monthParam]);

  useEffect(() => {
    loadAttendance();
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [monthParam]);

  useEffect(() => {
    const run = async () => {
      try {
        const year = monthParam.slice(0, 4);
        if (!/^\d{4}$/.test(year)) return;
        const res = await getTimesheets({ year: Number(year), per_page: 50, page: 1 });
        const list = res.data?.items ?? [];
        const found =
          list.find((t) => t.attendance_month === monthParam) ||
          list.find((t) => t.month_key === monthParam) ||
          null;
        setMonthTimesheet(found);
      } catch {
        setMonthTimesheet(null);
      }
    };
    void run();
  }, [monthParam]);

  const formatDate = (dateString: string) => {
    const date = new Date(dateString);
    return date.toLocaleDateString('en-US', {
      month: 'short',
      day: 'numeric',
      year: 'numeric',
    });
  };

  const summary = useMemo(() => {
    const isDayOff = (entry: AttendanceEntry) => {
      if (entry.type !== 'attendance') return false;
      return (
        !entry.startTime &&
        !entry.finishTime &&
        !entry.totalHours &&
        isZeroDurationLabel(entry.breakDuration)
      );
    };

    const sumMinutes = entries.reduce((acc, e) => acc + (e.totalMinutes ?? 0), 0);
    const attendanceDays = entries.filter((e) => e.type === 'attendance' && !isDayOff(e)).length;
    const dayOffDays = entries.filter((e) => isDayOff(e)).length;
    const leaveDays = entries.filter((e) => e.type === 'leave').length;
    const holidayDays = entries.filter((e) => e.type === 'holiday').length;

    const hours = Math.floor(sumMinutes / 60);
    const mins = sumMinutes % 60;
    const hoursLabel =
      sumMinutes === 0 ? '—' : `${hours}h:${String(mins).padStart(2, '0')}m`;

    return {
      hoursLabel,
      attendanceDays,
      dayOffDays,
      leaveDays,
      holidayDays,
      totalDays: entries.length,
    };
  }, [entries]);

  const canDownloadMonthPdf = Boolean(
    monthTimesheet &&
      String(monthTimesheet.status || '').toLowerCase() === 'approved' &&
      (monthTimesheet.can_download_pdf !== false)
  );

  const handleDownloadMonthPdf = async () => {
    if (!monthTimesheet?.id || downloadingPdf) return;
    if (!canDownloadMonthPdf) return;
    try {
      setDownloadingPdf(true);
      const token = await tokenStorage.getAccessToken();
      if (!token) {
        showToast.error('Download report', 'Session expired. Please login again.');
        return;
      }

      const url =
        monthTimesheet.download_pdf_url ||
        getTimesheetDownloadPdfUrl(monthTimesheet.id);

      const period = (monthTimesheet.period_code || monthParam).replace(/[^0-9A-Za-z_-]/g, '');
      const dir = ReactNativeBlobUtil.fs.dirs.CacheDir;
      const path = `${dir}/elitehr_timesheet_${period}_${Date.now()}.pdf`;

      showToast.info('Downloading', 'Preparing your timesheet report…');
      const res = await ReactNativeBlobUtil.config({ path, fileCache: true }).fetch(
        'GET',
        url,
        { Authorization: `Bearer ${token}`, Accept: 'application/pdf' }
      );

      const info = res.info();
      const status = info?.status ?? 0;
      const headers = (info?.headers ?? {}) as Record<string, string>;
      const contentType = headers['content-type'] || headers['Content-Type'] || '';
      if (status >= 300) {
        throw new Error(`Download failed (HTTP ${status}).`);
      }
      if (!String(contentType).toLowerCase().includes('pdf')) {
        throw new Error('Server did not return a PDF.');
      }

      const filePath = res.path();
      if (Platform.OS === 'ios') {
        await ReactNativeBlobUtil.ios.openDocument(filePath);
      } else {
        ReactNativeBlobUtil.android.actionViewIntent(filePath, 'application/pdf');
      }
    } catch (e: any) {
      Alert.alert('Download report', e?.message || 'Could not download this report');
    } finally {
      setDownloadingPdf(false);
    }
  };

  const renderAttendanceCard = (entry: AttendanceEntry) => {
    if (entry.type === 'leave') {
      return (
        <View key={entry.id} style={styles.card}>
          <View style={styles.cardHeader}>
            <Text style={styles.dateIcon}>📅</Text>
            <View style={styles.dateInfo}>
              <Text style={styles.dateText}>
                {formatDate(entry.date)} ({entry.dayOfWeek})
              </Text>
            </View>
          </View>
          <View style={styles.leaveContainer}>
            <Text style={styles.leaveText}>Leave</Text>
            {entry.leaveType && (
              <Text style={styles.leaveTypeText}>{entry.leaveType}</Text>
            )}
          </View>
        </View>
      );
    }

    if (entry.type === 'holiday') {
      return (
        <View key={entry.id} style={styles.card}>
          <View style={styles.cardHeader}>
            <Text style={styles.dateIcon}>📅</Text>
            <View style={styles.dateInfo}>
              <Text style={styles.dateText}>
                {formatDate(entry.date)} ({entry.dayOfWeek})
              </Text>
            </View>
          </View>
          <View style={styles.holidayContainer}>
            <Text style={styles.holidayText}>Public Holiday</Text>
            {entry.holidayName && (
              <Text style={styles.holidayNameText}>{entry.holidayName}</Text>
            )}
          </View>
        </View>
      );
    }

    const isDayOff =
      !entry.startTime &&
      !entry.finishTime &&
      !entry.totalHours &&
      isZeroDurationLabel(entry.breakDuration);

    return (
      <View key={entry.id} style={styles.card}>
        <View style={styles.cardHeader}>
          <Text style={styles.dateIcon}>📅</Text>
          <View style={styles.dateInfo}>
            <Text style={styles.dateText}>
              {formatDate(entry.date)} ({entry.dayOfWeek})
            </Text>
          </View>
        </View>
        {isDayOff ? (
          <View style={styles.dayOffContainer}>
            <Text style={styles.dayOffText}>Day off</Text>
            <Text style={styles.dayOffSubText}>No working hours recorded</Text>
          </View>
        ) : (
          <View style={styles.timeRow}>
            <Text style={styles.timeRangeText}>
              {entry.startTime && entry.finishTime
                ? `${entry.startTime} - ${entry.finishTime}`
                : entry.startTime || entry.finishTime || '—'}
            </Text>
            <View style={styles.pillsColumn}>
              {!isZeroDurationLabel(entry.breakDuration) && (
                <View style={styles.breakPill}>
                  <Text style={styles.breakPillLabel}>Break</Text>
                  <Text style={styles.breakPillValue}>
                    {entry.breakDuration}
                  </Text>
                </View>
              )}
              <View style={styles.totalHoursPill}>
                <Text style={styles.totalHoursPillLabel}>Total</Text>
                <Text style={styles.totalHoursPillValue}>
                  {entry.totalHours ?? '—'}
                </Text>
              </View>
            </View>
          </View>
        )}
        {entry.notes && (
          <View style={styles.notesContainer}>
            <Text style={styles.notesText}>{entry.notes}</Text>
          </View>
        )}
      </View>
    );
  };

  return (
    <View style={styles.container}>
      <StatusBar barStyle="light-content" backgroundColor="#0d1a5a" />
      
      {/* Notch area - darker colored background */}
      <View style={[styles.notchArea, { height: insets.top }]} />

      {/* Header */}
      <View style={styles.header}>
        <TouchableOpacity
          style={styles.backButton}
          onPress={() => navigation.goBack()}
          activeOpacity={0.7}>
          <View style={styles.backRow}>
            <Ionicons name="arrow-back" size={18} color="#ffffff" />
            <Text style={styles.backButtonText}>Back</Text>
          </View>
        </TouchableOpacity>
        <Text style={styles.headerTitle}>Attendance</Text>
        <View style={styles.headerActions}>
          <TouchableOpacity
            style={styles.headerIconBtn}
            onPress={() => navigation.navigate('TeamWorkingToday')}
            activeOpacity={0.8}>
            <Ionicons name="people-outline" size={20} color="#ffffff" />
          </TouchableOpacity>
          <TouchableOpacity
            style={styles.headerIconBtn}
            onPress={() => navigation.navigate('TimesheetsList')}
            activeOpacity={0.8}>
            <Ionicons name="list-outline" size={20} color="#ffffff" />
          </TouchableOpacity>
          <TouchableOpacity
            style={styles.headerIconBtn}
            onPress={() => setShowFilters((v) => !v)}
            activeOpacity={0.8}>
            <Ionicons
              name={showFilters ? 'close' : 'options-outline'}
              size={20}
              color="#ffffff"
            />
          </TouchableOpacity>
        </View>
      </View>

      {/* Filters Section */}
      {showFilters && (
        <View style={styles.filtersContainer}>
          <View style={styles.filtersCard}>
            <View style={styles.filtersHeaderRow}>
              <View style={styles.filtersTitleRow}>
                <Ionicons name="calendar-outline" size={18} color="#1a237e" />
                <Text style={styles.filtersTitle}>Filter by month</Text>
              </View>
              <TouchableOpacity
                style={styles.filtersCloseButton}
                onPress={() => setShowFilters(false)}
                activeOpacity={0.7}>
                <Ionicons name="close" size={18} color="#1a237e" />
              </TouchableOpacity>
            </View>

            <TouchableOpacity
              style={styles.monthPickerRow}
              onPress={() => setShowMonthPicker(true)}
              activeOpacity={0.8}>
              <View style={styles.monthPickerLeft}>
                <Ionicons name="calendar-outline" size={18} color="#64748b" />
                <View style={{ flex: 1 }}>
                  <Text style={styles.monthPickerLabel}>Selected month</Text>
                  <Text style={styles.monthPickerValue}>{monthLabel(draftMonth)}</Text>
                </View>
              </View>
              <Ionicons name="chevron-down" size={18} color="#94a3b8" />
            </TouchableOpacity>

            {showMonthPicker && (
              <View style={styles.pickerWrap}>
                {Platform.OS === 'ios' && (
                  <View style={styles.pickerHeaderRow}>
                    <Text style={styles.pickerHeaderTitle}>Choose month</Text>
                    <TouchableOpacity
                      onPress={() => setShowMonthPicker(false)}
                      activeOpacity={0.8}
                      hitSlop={{ top: 10, bottom: 10, left: 10, right: 10 }}>
                      <Text style={styles.pickerDone}>Done</Text>
                    </TouchableOpacity>
                  </View>
                )}
                <DateTimePicker
                  value={pickerDate}
                  mode="date"
                  display={(Platform.OS === 'ios' ? (Platform.isPad ? 'inline' : 'spinner') : 'calendar') as any}
                  onChange={(event: any, date?: Date) => {
                    if (Platform.OS === 'android') {
                      if (event?.type === 'dismissed') {
                        setShowMonthPicker(false);
                        return;
                      }
                      const next = date ?? pickerDate;
                      setPickerDate(next);
                      setDraftMonth(dateToMonth(next));
                      setShowMonthPicker(false);
                      return;
                    }
                    const next = date ?? pickerDate;
                    setPickerDate(next);
                    setDraftMonth(dateToMonth(next));
                  }}
                  themeVariant="light"
                  textColor="#0f172a"
                />
              </View>
            )}

            <View style={styles.filterActionsRow}>
              <TouchableOpacity
                style={styles.secondaryButton}
                onPress={resetMonthFilter}
                activeOpacity={0.8}>
                <Text style={styles.secondaryButtonText}>This month</Text>
              </TouchableOpacity>
              <TouchableOpacity
                style={styles.primaryButton}
                onPress={applyMonthFilter}
                activeOpacity={0.8}>
                <Text style={styles.primaryButtonText}>Apply</Text>
              </TouchableOpacity>
            </View>
          </View>
        </View>
      )}

      <ScrollView
        style={styles.scrollView}
        contentContainerStyle={styles.scrollContent}
        refreshControl={
          <RefreshControl refreshing={refreshing} onRefresh={onRefresh} />
        }
        showsVerticalScrollIndicator={false}>
        {/* Month summary header */}
        <View style={styles.summaryCard}>
          <View style={styles.summaryTopRow}>
            <View style={styles.summaryMonthRow}>
              <Ionicons name="calendar-outline" size={18} color="#1a237e" />
              <View style={{ flex: 1 }}>
                <Text style={styles.summaryMonthTitle}>{monthLabel(appliedMonth)}</Text>
                <Text style={styles.summaryMonthSub}>
                  {summary.totalDays ? `${summary.totalDays} records` : 'No records'}
                </Text>
              </View>
            </View>
            <View style={styles.summaryTopActions}>
              {canDownloadMonthPdf && (
                <TouchableOpacity
                  style={[styles.pdfBtn, downloadingPdf && styles.pdfBtnDisabled]}
                  onPress={handleDownloadMonthPdf}
                  activeOpacity={0.85}
                  disabled={downloadingPdf}>
                  <Ionicons name="download-outline" size={16} color="#1a237e" />
                  <Text style={styles.pdfBtnText}>
                    {downloadingPdf ? 'Downloading…' : 'PDF'}
                  </Text>
                </TouchableOpacity>
              )}
              <TouchableOpacity
                style={styles.changeMonthBtn}
                onPress={() => setShowFilters(true)}
                activeOpacity={0.85}>
                <Ionicons name="options-outline" size={16} color="#1a237e" />
                <Text style={styles.changeMonthText}>Change</Text>
              </TouchableOpacity>
            </View>
          </View>

          <View style={styles.summaryGrid}>
            <View style={styles.summaryTile}>
              <Text style={styles.summaryTileLabel}>Total Hours</Text>
              <Text style={styles.summaryTileValue}>{summary.hoursLabel}</Text>
            </View>
            <View style={styles.summaryTile}>
              <Text style={styles.summaryTileLabel}>Attendance</Text>
              <Text style={styles.summaryTileValue}>{summary.attendanceDays}</Text>
            </View>
            <View style={styles.summaryTile}>
              <Text style={styles.summaryTileLabel}>Day off</Text>
              <Text style={styles.summaryTileValue}>{summary.dayOffDays}</Text>
            </View>
            <View style={styles.summaryTile}>
              <Text style={styles.summaryTileLabel}>Leave/Holiday</Text>
              <Text style={styles.summaryTileValue}>
                {summary.leaveDays + summary.holidayDays}
              </Text>
            </View>
          </View>
        </View>

        {isLoading && entries.length === 0 ? (
          <View style={styles.emptyContainer}>
            <Text style={styles.emptyText}>Loading attendance…</Text>
          </View>
        ) : entries.length === 0 ? (
          <View style={styles.emptyContainer}>
            <Text style={styles.emptyText}>No attendance records found</Text>
          </View>
        ) : (
          entries.map((entry) => renderAttendanceCard(entry))
        )}
      </ScrollView>
    </View>
  );
};

const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#f5f5f5',
  },
  notchArea: {
    backgroundColor: '#0d1a5a',
    width: '100%',
  },
  header: {
    backgroundColor: '#1a237e',
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: 20,
    paddingBottom: 16,
    paddingTop: 10,
  },
  backRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
  },
  backButton: {
    paddingVertical: 8,
    paddingHorizontal: 4,
  },
  backButtonText: {
    fontSize: 16,
    color: '#ffffff',
    fontWeight: '500',
  },
  headerTitle: {
    fontSize: 20,
    fontWeight: 'bold',
    color: '#ffffff',
  },
  headerActions: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
  },
  headerIconBtn: {
    paddingVertical: 8,
    paddingHorizontal: 10,
    borderRadius: 10,
    backgroundColor: 'rgba(255,255,255,0.14)',
  },
  filtersContainer: {
    backgroundColor: '#ffffff',
    paddingHorizontal: 16,
    paddingTop: 14,
    paddingBottom: 14,
    borderBottomWidth: 1,
    borderBottomColor: '#e0e0e0',
  },
  filtersCard: {
    backgroundColor: '#f8fafc',
    borderRadius: 14,
    padding: 14,
    borderWidth: 1,
    borderColor: '#e2e8f0',
  },
  filtersHeaderRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginBottom: 12,
  },
  filtersTitleRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
  },
  filtersTitle: {
    fontSize: 14,
    fontWeight: '700',
    color: '#0f172a',
  },
  filtersCloseButton: {
    width: 34,
    height: 34,
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: 10,
    backgroundColor: '#eef2ff',
  },
  monthPickerRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    borderWidth: 1,
    borderColor: '#e2e8f0',
    backgroundColor: '#ffffff',
    borderRadius: 12,
    paddingHorizontal: 12,
    paddingVertical: 12,
  },
  monthPickerLeft: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
    flex: 1,
    paddingRight: 12,
  },
  monthPickerLabel: {
    fontSize: 12,
    color: '#64748b',
    fontWeight: '700',
  },
  monthPickerValue: {
    marginTop: 2,
    fontSize: 14,
    color: '#0f172a',
    fontWeight: '800',
  },
  pickerWrap: {
    marginTop: 12,
    borderWidth: 1,
    borderColor: '#e2e8f0',
    backgroundColor: '#ffffff',
    borderRadius: 12,
    padding: 10,
  },
  pickerHeaderRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: 4,
    paddingBottom: 6,
  },
  pickerHeaderTitle: {
    fontSize: 13,
    fontWeight: '800',
    color: '#0f172a',
  },
  pickerDone: {
    fontSize: 13,
    fontWeight: '900',
    color: '#1a237e',
  },
  filterActionsRow: {
    flexDirection: 'row',
    gap: 12,
    marginTop: 14,
  },
  secondaryButton: {
    flex: 1,
    backgroundColor: '#ffffff',
    borderWidth: 1,
    borderColor: '#cbd5e1',
    paddingVertical: 12,
    borderRadius: 12,
    alignItems: 'center',
  },
  secondaryButtonText: {
    fontSize: 14,
    fontWeight: '700',
    color: '#1a237e',
  },
  primaryButton: {
    flex: 1,
    backgroundColor: '#1a237e',
    paddingVertical: 12,
    borderRadius: 12,
    alignItems: 'center',
  },
  primaryButtonText: {
    fontSize: 14,
    fontWeight: '700',
    color: '#ffffff',
  },
  scrollView: {
    flex: 1,
  },
  scrollContent: {
    padding: 16,
    paddingBottom: 100,
  },
  summaryCard: {
    backgroundColor: '#ffffff',
    borderRadius: 14,
    padding: 14,
    marginBottom: 12,
    borderWidth: 1,
    borderColor: '#e2e8f0',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.06,
    shadowRadius: 6,
    elevation: 3,
  },
  summaryTopRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 10,
  },
  summaryMonthRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
    flex: 1,
    paddingRight: 8,
  },
  summaryMonthTitle: {
    fontSize: 14,
    fontWeight: '900',
    color: '#0f172a',
  },
  summaryMonthSub: {
    marginTop: 2,
    fontSize: 12,
    fontWeight: '700',
    color: '#64748b',
  },
  changeMonthBtn: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    paddingVertical: 8,
    paddingHorizontal: 10,
    borderRadius: 999,
    backgroundColor: '#eef2ff',
  },
  changeMonthText: {
    fontSize: 12,
    fontWeight: '900',
    color: '#1a237e',
  },
  summaryTopActions: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
  },
  pdfBtn: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    paddingVertical: 8,
    paddingHorizontal: 10,
    borderRadius: 999,
    backgroundColor: '#ffffff',
    borderWidth: 1,
    borderColor: '#cbd5e1',
  },
  pdfBtnDisabled: {
    opacity: 0.7,
  },
  pdfBtnText: {
    fontSize: 12,
    fontWeight: '900',
    color: '#1a237e',
  },
  summaryGrid: {
    marginTop: 12,
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 10,
  },
  summaryTile: {
    flexGrow: 1,
    flexBasis: '47%',
    backgroundColor: '#f8fafc',
    borderWidth: 1,
    borderColor: '#e2e8f0',
    borderRadius: 12,
    paddingVertical: 10,
    paddingHorizontal: 12,
  },
  summaryTileLabel: {
    fontSize: 11,
    fontWeight: '800',
    color: '#64748b',
  },
  summaryTileValue: {
    marginTop: 4,
    fontSize: 15,
    fontWeight: '900',
    color: '#0f172a',
  },
  card: {
    backgroundColor: '#ffffff',
    borderRadius: 12,
    padding: 16,
    marginBottom: 12,
    shadowColor: '#000',
    shadowOffset: {
      width: 0,
      height: 2,
    },
    shadowOpacity: 0.1,
    shadowRadius: 3.84,
    elevation: 5,
  },
  cardHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 12,
  },
  dateIcon: {
    fontSize: 20,
    marginRight: 12,
  },
  dateInfo: {
    flex: 1,
  },
  dateText: {
    fontSize: 16,
    fontWeight: '600',
    color: '#212121',
  },
  timeInfo: {
    marginBottom: 8,
  },
  timeText: {
    fontSize: 16,
    fontWeight: '500',
    color: '#424242',
  },
  timeRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginTop: 2,
  },
  timeRangeText: {
    fontSize: 15,
    fontWeight: '500',
    color: '#424242',
    flexShrink: 1,
    paddingRight: 12,
  },
  pillsColumn: {
    alignItems: 'flex-end',
    gap: 8,
  },
  breakPill: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#f1f5f9',
    borderRadius: 999,
    paddingVertical: 6,
    paddingHorizontal: 10,
  },
  breakPillLabel: {
    fontSize: 12,
    color: '#475569',
    fontWeight: '600',
    marginRight: 6,
  },
  breakPillValue: {
    fontSize: 12,
    color: '#0f172a',
    fontWeight: '700',
  },
  totalHoursPill: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#eef2ff',
    borderRadius: 999,
    paddingVertical: 6,
    paddingHorizontal: 10,
  },
  totalHoursPillLabel: {
    fontSize: 12,
    color: '#3949ab',
    fontWeight: '600',
    marginRight: 6,
  },
  totalHoursPillValue: {
    fontSize: 12,
    color: '#1a237e',
    fontWeight: '700',
  },
  dayOffContainer: {
    backgroundColor: '#f8fafc',
    borderRadius: 10,
    paddingVertical: 12,
    paddingHorizontal: 14,
    marginTop: 2,
    borderWidth: 1,
    borderColor: '#e2e8f0',
  },
  dayOffText: {
    fontSize: 15,
    fontWeight: '700',
    color: '#0f172a',
  },
  dayOffSubText: {
    marginTop: 4,
    fontSize: 12,
    color: '#64748b',
  },
  detailsRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginBottom: 6,
  },
  detailLabel: {
    fontSize: 14,
    color: '#757575',
  },
  detailValue: {
    fontSize: 14,
    fontWeight: '500',
    color: '#212121',
  },
  notesContainer: {
    marginTop: 8,
    paddingTop: 8,
    borderTopWidth: 1,
    borderTopColor: '#e0e0e0',
  },
  notesText: {
    fontSize: 12,
    color: '#757575',
    fontStyle: 'italic',
  },
  leaveContainer: {
    backgroundColor: '#fff3e0',
    padding: 12,
    borderRadius: 8,
    marginTop: 8,
  },
  leaveText: {
    fontSize: 16,
    fontWeight: '600',
    color: '#e65100',
    marginBottom: 4,
  },
  leaveTypeText: {
    fontSize: 14,
    color: '#e65100',
  },
  holidayContainer: {
    backgroundColor: '#e3f2fd',
    padding: 12,
    borderRadius: 8,
    marginTop: 8,
  },
  holidayText: {
    fontSize: 16,
    fontWeight: '600',
    color: '#1976d2',
    marginBottom: 4,
  },
  holidayNameText: {
    fontSize: 14,
    color: '#1976d2',
  },
  emptyContainer: {
    alignItems: 'center',
    justifyContent: 'center',
    paddingVertical: 60,
  },
  emptyText: {
    fontSize: 16,
    color: '#757575',
  },
});

export default AttendanceListScreen;

